name: flutter_quanttide_finance
description: Flutter data exposure shell for quanttide-finance-toolkit.
version: 0.1.0
homepage: https://github.com/quanttide/quanttide-finance-toolkit
repository: https://github.com/quanttide/quanttide-finance-toolkit
issue_tracker: https://github.com/quanttide/quanttide-finance-toolkit/issues

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  quanttide_finance:
    path: ../dart
  http: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
