"""M1: add core entities

Revision ID: 571dd6946d4b
Revises: 
Create Date: 2026-05-30 17:08:10.567381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '571dd6946d4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_channel', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', sqlite.JSON(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('evidence_refs', sqlite.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('ingestion_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('normalized_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('primary_source_id', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('person', sa.String(length=255), nullable=True),
    sa.Column('counterparty', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('normalization_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['primary_source_id'], ['source_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classification_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('normalized_record_id', sa.Integer(), nullable=False),
    sa.Column('taxonomy', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('classifier_kind', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['normalized_record_id'], ['normalized_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_record_id', sa.Integer(), nullable=False),
    sa.Column('normalized_record_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['normalized_record_id'], ['normalized_record.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_link')
    op.drop_table('classification_result')
    op.drop_table('normalized_record')
    op.drop_table('source_record')
    # ### end Alembic commands ###
