name: cli

on:
  push:
    paths:
      - 'src/cli/**'
  pull_request:
    paths:
      - 'src/cli/**'

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/cli
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build
      - run: cargo test
